### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m2-evaluacion-intermedia-anajd#1]
Really cool job @anajd !!!

Here you have some tips to improve the exercise:

- [x] On page load, execute 'getRandomNumber' function and store the returned value on a constant to work with it later.
- [x] If you call 'getRandomNumer' function inside the event callback, you will be creating a new random number each time the user clicks the button. That makes the game really complex and the hints will not have sense. Let's generate the random number when the page loads instead.
- [x] Define the logic to make the counter work
- [x] Don't use a `return` statement in a callback to return a value because it's not possible to get the value in the `addEventListener`
- [x] Remember to convert input value string to a number
- [x] Extract the feedback painter to a function
- [x] Fix the if's structure: check for one option, then the other and then for the rest is enough with an `else` statement
- [x] Don't use an object to resolve the counter, a good old constant will suffice ;)
- [x] Move the feedback logic to a function an execute it on each click
- [x] Move you counter logic into a function and execute it on each click
- [x] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?
- [x] Inputs must have a type attribute set to a valid value (text, number, mail, button..)

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Let me know if you have any doubts ;)

Go for it!!

**Comment by anajd** [comment]
I did the tips and add some new functions.
I did the CSS different too. :)

**Comment by oneeyedman** [comment]
Excellent job, @anajd !!!

You rock! Here you have a cool gif!
![you rock](https://media.giphy.com/media/5C0b4tU550kNGRmJrU/giphy-downsized.gif)
